version: '3.8'

services:
  # Nginx Web Server
  nginx:
    build:
      context: ./docker/nginx
      dockerfile: Dockerfile
    container_name: yii2_nginx
    ports:
      - "8080:80"      # Frontend
      - "8081:81"      # Backend
      - "8082:82"      # API
      - "443:443"
    volumes:
      - ./api:/var/www/api
      - ./backend:/var/www/backend
      - ./frontend:/var/www/frontend
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./docker/nginx/api.conf:/etc/nginx/conf.d/api.conf
      - ./docker/nginx/backend.conf:/etc/nginx/conf.d/backend.conf
      - ./docker/nginx/frontend.conf:/etc/nginx/conf.d/frontend.conf
      - nginx_logs:/var/log/nginx
    depends_on:
      - php-fpm
    networks:
      - frontend_net
      - backend_net
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # PHP-FPM 8.3
  php-fpm:
    build:
      context: ./docker/php-fpm
      dockerfile: Dockerfile
      args:
        PHP_VERSION: "8.3"
    container_name: yii2_php_fpm
    ports:
      - "9001:9001"  # FPM status endpoint
    volumes:
      - ./api:/var/www/api
      - ./backend:/var/www/backend
      - ./frontend:/var/www/frontend
      - ./common:/var/www/common
      - ./console:/var/www/console
      - ./migrations:/var/www/migrations
      - ./vendor:/var/www/vendor
      - ./composer.json:/var/www/composer.json
      - ./composer.lock:/var/www/composer.lock
      - ./docker/php-fpm/php.ini:/usr/local/etc/php/php.ini
      - ./docker/php-fpm/www.conf:/usr/local/etc/php-fpm.d/www.conf
      - ./docker/php-fpm/supervisord.conf:/etc/supervisor/conf.d/supervisord.conf
      - php_logs:/var/log/php-fpm
    environment:
      - PHP_IDE_CONFIG=serverName=Docker
      - XDEBUG_MODE=${XDEBUG_MODE:-off}
    depends_on:
      pgsql:
        condition: service_healthy
      redis:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
    networks:
      - backend_net
    restart: unless-stopped
    # healthcheck:
    #   test: ["CMD-SHELL", "php-fpm -t"]
    #   interval: 30s
    #   timeout: 10s
    #   retries: 3
    #   start_period: 60s

  # PostgreSQL 15
  pgsql:
    build:
      context: ./docker/postgresql
      dockerfile: Dockerfile
    container_name: yii2_pgsql
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: ${DB_NAME:-yii2advanced}
      POSTGRES_USER: ${DB_USERNAME:-yii2}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-secret}
      POSTGRES_ROOT_PASSWORD: ${DB_ROOT_PASSWORD:-root_secret}
    volumes:
      - pgsql_data:/var/lib/postgresql/data
      - ./docker/postgresql/init:/docker-entrypoint-initdb.d
    networks:
      - backend_net
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "${DB_USERNAME:-yii2}"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
    deploy:
      resources:
        limits:
          cpus: '2'
          memory: 2G
        reservations:
          cpus: '0.5'
          memory: 512M

  # Redis 7
  redis:
    image: redis:7-alpine
    container_name: yii2_redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
      - ./docker/redis/redis.conf:/usr/local/etc/redis/redis.conf
    command: redis-server /usr/local/etc/redis/redis.conf
    networks:
      - backend_net
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 20s
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 512M
        reservations:
          cpus: '0.25'
          memory: 128M

  # RabbitMQ 3.12
  rabbitmq:
    build:
      context: ./docker/rabbitmq
      dockerfile: Dockerfile
    container_name: yii2_rabbitmq
    ports:
      - "5672:5672"   # AMQP
      - "15672:15672" # Management UI
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_USER:-guest}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_PASSWORD:-guest}
      RABBITMQ_DEFAULT_VHOST: ${RABBITMQ_VHOST:-/}
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
      - ./docker/rabbitmq/rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf
      - ./docker/rabbitmq/enabled_plugins:/etc/rabbitmq/enabled_plugins
    networks:
      - backend_net
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "ping"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 1G
        reservations:
          cpus: '0.25'
          memory: 256M

  # Prometheus (Optional - Metrics)
  prometheus:
    image: prom/prometheus:latest
    container_name: yii2_prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./docker/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/etc/prometheus/console_libraries'
      - '--web.console.templates=/etc/prometheus/consoles'
      - '--web.enable-lifecycle'
    networks:
      - backend_net
    restart: unless-stopped
    profiles:
      - monitoring

  # Grafana (Optional - Dashboards)
  grafana:
    image: grafana/grafana:latest
    container_name: yii2_grafana
    ports:
      - "3000:3000"
    environment:
      GF_SECURITY_ADMIN_USER: ${GRAFANA_USER:-admin}
      GF_SECURITY_ADMIN_PASSWORD: ${GRAFANA_PASSWORD:-admin}
      GF_INSTALL_PLUGINS: redis-datasource
    volumes:
      - grafana_data:/var/lib/grafana
      - ./docker/grafana/dashboards:/etc/grafana/provisioning/dashboards
      - ./docker/grafana/datasources:/etc/grafana/provisioning/datasources
    depends_on:
      - prometheus
    networks:
      - backend_net
    restart: unless-stopped
    profiles:
      - monitoring

networks:
  frontend_net:
    driver: bridge
  backend_net:
    driver: bridge

volumes:
  pgsql_data:
    driver: local
  redis_data:
    driver: local
  rabbitmq_data:
    driver: local
  prometheus_data:
    driver: local
  grafana_data:
    driver: local
  nginx_logs:
    driver: local
  php_logs:
    driver: local
