global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'php-fpm'
    static_configs:
      - targets: ['php-fpm:9001']

  - job_name: 'nginx'
    static_configs:
      - targets: ['nginx:80']

  - job_name: 'rabbitmq'
    static_configs:
      - targets: ['rabbitmq:15672']
